"""add exercise_sets

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-08 22:27:33.765200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.String(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sets_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_sets_exercise'), ['exercise'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_sets_log_id'), ['log_id'], unique=False)
        batch_op.create_index('ix_exercise_sets_user_exercise_date', ['user_id', 'exercise', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_sets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_sets_user_id'))
        batch_op.drop_index('ix_exercise_sets_user_exercise_date')
        batch_op.drop_index(batch_op.f('ix_exercise_sets_log_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_sets_exercise'))
        batch_op.drop_index(batch_op.f('ix_exercise_sets_date'))

    op.drop_table('exercise_sets')
    # ### end Alembic commands ###
