"""식단 구성 원칙과 공식 레시피 패턴의 provenance."""

EVIDENCE_SOURCES = (
    {
        "id": "acsm_2016",
        "organization": "Academy of Nutrition and Dietetics / Dietitians of Canada / ACSM",
        "title": "Nutrition and Athletic Performance: Joint Position Statement",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26891166/",
        "evidence_type": "joint_position_statement",
        "summary": "운동 수행과 회복을 위해 음식과 수분의 종류·양·타이밍을 훈련 상황에 맞게 선택한다.",
        "publication_year": 2016,
    },
    {
        "id": "issn_protein_2017",
        "organization": "International Society of Sports Nutrition",
        "title": "ISSN Position Stand: Protein and Exercise",
        "url": "https://jissn.biomedcentral.com/articles/10.1186/s12970-017-0177-8",
        "evidence_type": "position_stand",
        "summary": "운동인은 하루에 걸쳐 양질의 단백질을 분배하고 가능하면 일반 식품 공급원을 우선한다.",
        "publication_year": 2017,
    },
    {
        "id": "issn_timing_2017",
        "organization": "International Society of Sports Nutrition",
        "title": "ISSN Position Stand: Nutrient Timing",
        "url": "https://jissn.biomedcentral.com/articles/10.1186/s12970-017-0189-4",
        "evidence_type": "position_stand",
        "summary": "훈련 연료와 회복 맥락에서 탄수화물과 단백질의 조합 및 섭취 시점을 고려한다.",
        "publication_year": 2017,
    },
    {
        "id": "usda_myplate",
        "organization": "USDA MyPlate",
        "title": "What Is MyPlate and Protein Foods",
        "url": "https://www.myplate.gov/eat-healthy/what-is-myplate",
        "evidence_type": "government_dietary_guidance",
        "summary": "과일·채소·곡물·단백질·유제품 또는 강화 대체식품을 다양하게 구성하고 단백질원을 순환한다.",
        "publication_year": 2020,
    },
    {
        "id": "usda_fdc",
        "organization": "USDA FoodData Central",
        "title": "Foundation Foods Documentation",
        "url": "https://fdc.nal.usda.gov/Foundation_Foods_Documentation/",
        "evidence_type": "government_nutrient_database",
        "summary": "향후 표준 중량과 조리 상태가 확보된 식재료의 영양값을 FDC ID로 연결하기 위한 공식 데이터 원천이다.",
        "publication_year": 2024,
    },
    {
        "id": "ais_recipes",
        "organization": "Australian Institute of Sport",
        "title": "AIS Nutrition Recipes",
        "url": "https://www.ais.gov.au/nutrition/recipes",
        "evidence_type": "sports_dietitian_recipe_collection",
        "summary": "스포츠영양사가 제공하는 운동인용 일반식·간편식 조합의 패턴을 참고한다.",
        "publication_year": 2026,
    },
    {
        "id": "ais_chicken_pasta",
        "organization": "Australian Institute of Sport",
        "title": "Pasta with Chicken and Corn",
        "url": "https://www.ais.gov.au/nutrition/recipes/pasta_with_chicken_and_corn",
        "evidence_type": "sports_dietitian_recipe",
        "summary": "닭고기·파스타·옥수수·버섯·토마토 기반의 훈련 연료 조합을 참고한다.",
        "publication_year": 2018,
    },
    {
        "id": "ais_lamb_curry",
        "organization": "Australian Institute of Sport",
        "title": "Lachie's Rogan Josh with Spinach and Potatoes",
        "url": "https://www.ais.gov.au/nutrition/recipes/lachies_rogan_josh_with_spinach_and_potatoes",
        "evidence_type": "sports_dietitian_recipe",
        "summary": "양고기·쌀·감자·시금치·콩·요거트의 혼합식 패턴을 참고한다.",
        "publication_year": 2018,
    },
    {
        "id": "ais_fruit_smoothie",
        "organization": "Australian Institute of Sport",
        "title": "Any Fruit Smoothie",
        "url": "https://www.ais.gov.au/nutrition/recipes/any_fruit_smoothie",
        "evidence_type": "sports_dietitian_recipe",
        "summary": "우유·요거트·과일을 이용한 간편한 탄수화물·단백질 간식 패턴을 참고한다.",
        "publication_year": 2018,
    },
    {
        "id": "ais_mango_smoothie",
        "organization": "Australian Institute of Sport",
        "title": "Mango Smoothie",
        "url": "https://www.ais.gov.au/nutrition/recipes/mango_smoothie",
        "evidence_type": "sports_dietitian_recipe",
        "summary": "우유와 망고 기반의 간편한 운동 전후 간식 패턴을 참고한다.",
        "publication_year": 2018,
    },
)


__all__ = ["EVIDENCE_SOURCES"]
